# Generated by Django 4.2.3 on 2023-07-17 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='category',
            field=models.CharField(choices=[('starter', 'starter'), ('breakfast', 'breakfast'), ('lunch', 'lunch'), ('dinner', 'dinner')], max_length=10),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
